Chapter1
SttavoS/Learn4Elixir pull request #1
Opened 2023-10-17 23:05 UTC by SttavoS

### Solução do Livebook Nº 1

cc @anabastos @camilotk @cherry @cyytrus @digzom @douglastofoli @eulixir @lanjoni @OtavioSC @zoedsoupe

2023-10-18 01:45 UTC, Camilotk requested changes

2023-10-18 01:45 UTC, Camilotk commented on chapters/chapter1.livemd
> +  superficie: "7,48×10^7",
Esse é um exercício justamente de Modelagem, por isso não tem resposta errada. Porém, talvez seja interessante dar uma olhada novamente na parte de representação de inteiros do livebook e tem uma que pode ajudar a representar esse valor como inteiro de uma forma bem simples de escrever.

2023-10-18 01:45 UTC, Camilotk commented on chapters/chapter1.livemd
> +tmp = Enum.at(resposta_completa, 4)
Aqui pode ser interessante usar Pattern Matching. Não tem resposta "errada" o objetivo é chegar ao que é pedido. Cada exercício é pensado como um "problema" e a ideia é que não tem um jeito "certo" de resolver um problema, no máximo uma forma "pessoalmente satisfatória" que é o quanto você está feliz com a foma como resolveu. Se atende a solução do problema tanto faz usar find, usar filter, pattern matching... é uma questão de como você vai fazer.

Vamos recomendar que use Pattern Matching porque é bacana que você treine o uso dos padrões para aprendê-los. É muito útil, mas se quiser resolver de outra forma.

2023-10-18 01:45 UTC, Camilotk commented on chapters/chapter1.livemd
> +b = 2
Os valores da equação não estão certos. O resultado dessa formula quadrática é uma única raíz.

2023-10-19 00:14 UTC, SttavoS commented on chapters/chapter1.livemd
> +  superficie: "7,48×10^7",
Feito

2023-10-19 00:15 UTC, SttavoS commented on chapters/chapter1.livemd
> +tmp = Enum.at(resposta_completa, 4)
Confesso que não entendi como poderia fazer com pattern matching, achei mais fácil fazer usando o `find`, que é o que eu usaria no JS.

2023-10-23 03:13 UTC, Camilotk approved these changes

2023-10-23 11:33 UTC, eulixir commented
Opa @SttavoS, como vai?

Passando aqui só para lembrar de colocar a tag do hacktoberfest :)

2023-10-25 00:21 UTC, merged